/**
 * Concept views for the cast, from the character table, on Hugging Face.
 *
 *   node tools/genconcept.mjs corvin          # one character
 *   node tools/genconcept.mjs --all           # everybody who has no view yet
 *   node tools/genconcept.mjs vesna --force   # regenerate one that exists
 *
 * The mesh half of this pipeline (`genmesh.mjs`) has always read its views from
 * `assets/concepts/` and said, in as many words, that generating them was somebody else's
 * job — which in practice meant one character was generated by hand through a Python script
 * in a sibling repository and the other thirteen were never generated at all. So the cast
 * stayed on the stock models the reference picks by hash, which is not what "design the
 * characters" means.
 *
 * The prompt is built from `godot/data/characters.json` rather than typed: build, height,
 * hair and every garment colour are already in the table that decides who these people are,
 * and a prompt written by hand beside that table is a second description that drifts. Colour
 * words come from the hex by nearest match, so "#8aa25a" reaches the image model as "olive
 * green" instead of as six characters it will ignore.
 *
 * Two things the reconstruction cares about are stated at length rather than assumed:
 *
 *   **The T-pose.** `rig_character.py` finds the shoulder line from the far-lateral
 *   vertices — the outstretched hands are the only geometry out at the sides — so an A-pose
 *   puts the shoulders in the pelvis and the arms deform from the wrong pivot. Image models
 *   drift back to a natural stance given any latitude, so the pose is said four ways.
 *
 *   **No ground.** Anything that reads as a floor becomes a slab under the figure, and a
 *   cast shadow implies a floor. `isolate.mjs` mattes the background afterwards, but a
 *   plinth that was drawn in perspective cannot be matted out.
 *
 * The Space is `black-forest-labs/FLUX.1-schnell`, four steps, on the same token as the
 * mesh Space. Gradio 5 puts its routes under `/gradio_api`; the Hunyuan3D Space is Gradio
 * 4.44 and puts them at the root, which is why `hyspace.mjs` cannot simply be reused.
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(new URL('../package.json', import.meta.url)));
const say = (s = '') => console.log(s);

const SPACE = 'black-forest-labs-flux-1-schnell.hf.space';
const STEPS = 4;
const WIDTH = 832;
const HEIGHT = 1216;

function loadToken() {
  if (process.env.HF_TOKEN) return 'the environment';
  const envFile = path.join(process.env.HOME ?? '', 'Documents', 'kingdom-hearts', '.env');
  if (!fs.existsSync(envFile)) return null;
  for (const line of fs.readFileSync(envFile, 'utf8').split('\n')) {
    const [key, ...rest] = line.split('=');
    if (key.trim() === 'HF_TOKEN' && rest.length) {
      const value = rest.join('=').trim().replace(/^['"]|['"]$/g, '');
      if (value) { process.env.HF_TOKEN = value; return 'kingdom-hearts/.env'; }
    }
  }
  return null;
}

/**
 * Colour words, because a hex is not a description.
 *
 * Nearest match in plain RGB. A perceptual distance would be more correct and would change
 * none of these answers: the palette is twenty-six well-separated words and the table's
 * colours are not close calls.
 */
const COLOUR_WORDS = {
  black: '#111111', charcoal: '#333333', 'dark grey': '#555555', grey: '#888888',
  'light grey': '#bbbbbb', white: '#f2f2f2', cream: '#efe3c8', tan: '#d2a679',
  brown: '#7c4a24', 'dark brown': '#4b2e18', russet: '#8a4b2a', rust: '#b1552a',
  orange: '#e07b2a', gold: '#d8ac31', amber: '#c98f1e', yellow: '#e8d84a',
  olive: '#8a9a3a', 'olive green': '#8aa25a', green: '#3f8a4a', 'dark green': '#2c5a45',
  teal: '#2f7d7a', 'sky blue': '#6fb2ff', blue: '#3a5fae', navy: '#2b3a6b',
  indigo: '#33477c', violet: '#6b46a3', magenta: '#a5348a', crimson: '#8b2a2c',
  red: '#b34a41', pink: '#e2909a', 'pale skin': '#efd3bb', 'light tan skin': '#e7c39c',
  'mid brown skin': '#cf9c72', 'deep brown skin': '#8d5a3b',
};

function nearestWord(hex, only = null) {
  const to = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
  const [r, g, b] = to(hex);
  let best = null;
  let bestDistance = Infinity;
  for (const [word, value] of Object.entries(COLOUR_WORDS)) {
    if (only && !only.includes(word)) continue;
    const [wr, wg, wb] = to(value);
    const distance = (r - wr) ** 2 + (g - wg) ** 2 + (b - wb) ** 2;
    if (distance < bestDistance) { bestDistance = distance; best = word; }
  }
  return best;
}

const SKIN_WORDS = ['pale skin', 'light tan skin', 'mid brown skin', 'deep brown skin'];
const HAIR = {
  long: 'long loose hair', ponytail: 'hair tied back in a ponytail', short: 'short hair',
  topknot: 'hair in a topknot', braid: 'a long braid', bob: 'a straight bob',
  wild: 'wild matted hair', bald: 'a shaved head',
};

/**
 * The pose, said four ways. See the note at the top: this is the difference between a rig
 * that fits and arms that pivot from the hips.
 */
const T_POSE = 'standing in a strict symmetrical T-pose, both arms stretched straight out '
  + 'horizontally to the sides at exactly shoulder height, palms down, fingers together, '
  + 'legs straight and slightly apart, feet flat and parallel, facing the camera directly, '
  + 'full body visible from head to feet, arms not lowered, arms not bent, no weapon, no props';

const GROUND = 'plain flat light grey seamless background, no floor, no ground plane, '
  + 'no pedestal, no base, no cast shadow, no scenery, isolated on a plain background';

/** What a build word means to somebody drawing a body. */
const BUILD = {
  slim: 'slim', normal: 'ordinary build', athletic: 'athletic', heavy: 'heavy-set',
  hulking: 'huge and broad-shouldered', child: 'small and slight',
};

function promptFor(character) {
  const look = character.look ?? {};
  const colours = look.colors ?? {};
  const word = (key, only) => (colours[key] ? nearestWord(colours[key], only) : null);
  const garments = [];
  const push = (colour, thing) => { if (colour) garments.push(`${colour} ${thing}`); };
  push(word('torso'), 'tunic');
  push(word('accent'), 'trim and fittings');
  push(word('legs'), 'trousers');
  push(word('boots'), 'leather boots');
  push(word('gloves'), 'gloves');
  push(word('cape'), 'half-cape over one shoulder');
  push(word('metal'), 'metal plating');
  if (look.buckle) garments.push('a large belt buckle');

  // Stylised rather than photoreal, and the same for everybody. The world these people walk
  // through is flat-shaded models and hand-painted plates; a photographic party standing in
  // it would read as a different game — and three of the fourteen are children, which is not
  // a thing to render photographically.
  const height = Number(look.height ?? 1.7);
  const build = BUILD[String(look.build ?? 'normal')] ?? 'ordinary build';
  const hair = HAIR[String(look.hair ?? 'short')] ?? 'short hair';
  const skin = word('skin', SKIN_WORDS) ?? 'light tan skin';
  const hairColour = word('hair') ?? 'brown';

  return [
    'stylised 3D game character reference sheet, single character, front view,',
    `${build}, ${height.toFixed(2)} metres tall,`,
    `${character.role ?? 'adventurer'} in a worn fantasy world — ${character.title ?? ''};`,
    `${hairColour} ${hair}, ${skin};`,
    `wearing ${garments.join(', ')};`,
    'clean readable silhouette, believable cloth and leather with visible weave and wear,',
    'physically based materials, even soft studio lighting, sharp focus,',
    T_POSE + ';',
    GROUND,
  ].join(' ').replace(/\s+/g, ' ').trim();
}

// --- the Space ---------------------------------------------------------------

async function generate(prompt, seed) {
  const headers = {
    'Content-Type': 'application/json',
    ...(process.env.HF_TOKEN ? { Authorization: `Bearer ${process.env.HF_TOKEN}` } : {}),
  };
  const started = await fetch(`https://${SPACE}/gradio_api/call/infer`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ data: [prompt, seed, false, WIDTH, HEIGHT, STEPS] }),
  });
  if (!started.ok) throw new Error(`the Space refused the job: HTTP ${started.status}`);
  const { event_id: id } = await started.json();
  if (!id) throw new Error('the Space returned no event id');

  // The result arrives as an SSE stream: `event: complete` carries the data, `event: error`
  // carries a quota message worth reading rather than retrying against.
  const stream = await fetch(`https://${SPACE}/gradio_api/call/infer/${id}`, { headers });
  if (!stream.ok) throw new Error(`could not read the result stream: HTTP ${stream.status}`);
  const text = await stream.text();
  let payload = null;
  let failure = null;
  for (const block of text.split('\n\n')) {
    const kind = block.match(/^event: (\w+)/m)?.[1];
    const data = block.match(/^data: (.*)$/m)?.[1];
    if (!kind || !data) continue;
    if (kind === 'complete') payload = JSON.parse(data);
    if (kind === 'error') failure = data;
  }
  if (failure) throw new Error(`the Space failed: ${failure}`);
  if (!payload) throw new Error('the Space completed without a result');
  const url = payload[0]?.url ?? payload[0]?.path;
  if (!url) throw new Error(`no image in the result: ${JSON.stringify(payload).slice(0, 200)}`);
  const image = await fetch(url.startsWith('http') ? url
    : `https://${SPACE}/gradio_api/file=${url}`, { headers });
  if (!image.ok) throw new Error(`could not download the view: HTTP ${image.status}`);
  return { bytes: Buffer.from(await image.arrayBuffer()), seed: payload[1] ?? seed };
}

// --- the run -----------------------------------------------------------------

const args = process.argv.slice(2);
const force = args.includes('--force');
const all = args.includes('--all');
const named = args.filter((a) => !a.startsWith('--'));

const characters = JSON.parse(fs.readFileSync(
  path.join(root, 'godot', 'data', 'characters.json'), 'utf8'));
const conceptDir = path.join(root, 'assets', 'concepts');
fs.mkdirSync(conceptDir, { recursive: true });

const wanted = (all ? Object.keys(characters) : named).filter((id) => {
  if (!characters[id]) {
    say(`\x1b[31mFAIL\x1b[0m — no character called "${id}"`);
    process.exit(1);
  }
  return true;
});
if (!wanted.length) {
  say('Usage: node tools/genconcept.mjs <character…> [--all] [--force]');
  process.exit(2);
}

const source = loadToken();
say(`\x1b[1mConcept views from ${SPACE}\x1b[0m`);
say(`  token     ${source ?? '\x1b[33mnone — the anonymous pool\x1b[0m'}`);
say(`  size      ${WIDTH}×${HEIGHT}, ${STEPS} steps`);
say();

let made = 0;
for (const id of wanted) {
  const out = path.join(conceptDir, `${id}-front.png`);
  if (fs.existsSync(out) && !force) {
    say(`  ${id.padEnd(10)} \x1b[2mkept\x1b[0m ${path.relative(root, out)}`);
    continue;
  }
  const prompt = promptFor(characters[id]);
  // Seeded from the name, so a regeneration of one character is the same character.
  const seed = [...id].reduce((n, c) => (n * 31 + c.charCodeAt(0)) >>> 0, 7);
  try {
    const { bytes } = await generate(prompt, seed % 2_000_000);
    // Gradio 5 hands back a WebP with a `.png` name, and `isolate.mjs` reads PNG — it died on
    // "unrecognised content at end of stream", which is what a decoder says when it has been
    // handed the wrong format rather than a corrupt file. Converted here rather than taught to
    // every reader downstream.
    fs.writeFileSync(`${out}.download`, bytes);
    execFileSync('sips', ['-s', 'format', 'png', `${out}.download`, '--out', out],
      { stdio: 'ignore' });
    fs.rmSync(`${out}.download`);
    made++;
    say(`  ${id.padEnd(10)} \x1b[32mmade\x1b[0m ${(bytes.length / 1024).toFixed(0)}KB  `
      + `${path.relative(root, out)}`);
  } catch (err) {
    say(`  ${id.padEnd(10)} \x1b[31mfailed\x1b[0m ${err.message}`);
  }
}

say();
say(`\x1b[32mOK\x1b[0m — ${made} view(s) generated. Next: `
  + 'node tools/isolate.mjs <id>-front && node tools/genmesh.mjs <id> --textured --front-only');
